import img1 from "../src/assets/img/product/product1.png";

export const PRODUCTS = [
  {
    id: 1,
    img: img1,
    sale: "sale",
    title: "Jacket, Women",
    product_title: "Oversize Cotton Dress",
    current_price: 110,
    old_price: 78,
    color: "blue",
  },

  {
    id: 2,
    img: img1,
    sale: "sale",
    title: "Jacket, Women",
    product_title: "  Boxy Denim Jacket",
    current_price: 110,
    old_price: 78,
    color: "blue",
  },
  {
    id: 3,
    img: img1,
    sale: "sale",
    title: "Jacket, Women",
    product_title: "Square Shoulder Bag",
    current_price: 110,
    old_price: 78,
    color: "blue",
  },
  {
    id: 4,
    img: img1,
    sale: "sale",
    title: "Jacket, Women",
    product_title: "Oversize Cotton Dress",
    current_price: 110,
    old_price: 78,
    color: "blue",
  },

  {
    id: 5,

    img: img1,
    sale: "sale",
    title: "Jacket, Women",
    product_title: "Oversize Cotton Dress",
    current_price: 110,
    old_price: 78,
    color: "blue",
  },
  {
    id: 6,
    img: img1,
    sale: "sale",
    title: "Jacket, Women",
    product_title: "Oversize Cotton Dress",
    current_price: 110,
    old_price: 78,
    color: "blue",
  },
  {
    id: 7,

    img: img1,
    sale: "sale",
    title: "Jacket, Women",
    product_title: "Oversize Cotton Dress",
    current_price: 110,
    old_price: 78,
    color: "blue",
  },

  {
    id: 8,

    img: img1,
    sale: "sale",
    title: "Jacket, Women",
    product_title: "Oversize Cotton Dress",
    current_price: 110,
    old_price: 78,
    color: "blue",
  },
  {
    id: 9,
    img: img1,
    sale: "sale",
    title: "Jacket, Women",
    product_title: "Oversize Cotton Dress",
    current_price: 110,
    old_price: 78,
    color: "blue",
  },
  {
    id: 10,
    img: img1,
    sale: "sale",
    title: "Jacket, Women",
    product_title: "Oversize Cotton Dress",
    current_price: 110,
    old_price: 78,
    color: "blue",
  },

  {
    id: 11,
    img: img1,
    sale: "sale",
    title: "Jacket, Women",
    product_title: "Oversize Cotton Dress",
    current_price: 110,
    old_price: 78,
    color: "blue",
  },
  {
    id: 12,
    img: img1,
    sale: "sale",
    title: "Jacket, Women",
    product_title: "Oversize Cotton Dress",
    current_price: 110,
    old_price: 78,
    color: "blue",
  },
  {
    id: 13,
    img: img1,
    sale: "sale",
    title: "Jacket, Women",
    product_title: "Oversize Cotton Dress",
    current_price: 110,
    old_price: 78,
    color: "blue",
  },
  {
    id: 14,
    img: img1,
    sale: "sale",
    title: "Jacket, Women",
    product_title: "Oversize Cotton Dress",
    current_price: 110,
    old_price: 78,
    color: "blue",
  },
  {
    id: 15,
    img: img1,
    sale: "sale",
    title: "Jacket, Women",
    product_title: "Oversize Cotton Dress",
    current_price: 110,
    old_price: 78,
    color: "blue",
  },
  {
    id: 16,
    img: img1,
    sale: "sale",
    title: "Jacket, Women",
    product_title: "Oversize Cotton Dress",
    current_price: 110,
    old_price: 78,
    color: "blue",
  },
];






